name: Deploy to AWS EKS

on:
  push:
    branches:
      - main

jobs:
  main:
    name: OpenID Connect (OIDC) IAM role -> Another IAM role
    runs-on: ubuntu-latest
    # note: permissions required to fetch OpenID Connect token and allow actions/checkout
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Assume role
        uses: magnetikonline/action-aws-iam-assume-role@v1
        with:
          web-identity-role-arn: arn:aws:iam::102057119514:role/githubactions-test
          assume-role-arn: arn:aws:iam::102057119514:oidc-provider/token.actions.githubusercontent.com
          aws-region: us-east-1
          # optional inputs
          # assume-role-duration-seconds: 6000
          # assume-role-session-name: GitHubActions

      # IAM role assumed via AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY/AWS_SESSION_TOKEN
      - name: whoami
        run: aws sts get-caller-identity
          
     # - name: configure aws credentials
     #   uses: aws-actions/configure-aws-credentials@v1
     #   with:
     #    role-to-assume: arn:aws:iam::102057119514:role/oidc-test-01
        # role-session-name: samplerolesession  

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Format
      #   run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false

      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve -input=false
